export const ALERT_DATA_SOURCE = 'sample'

export const ALERT_ZONE_SAMPLES = [
  {
    postcode: '3004',
    suburb: 'Southbank & Domain',
    council: 'City of Melbourne',
    pressureScore: 91,
    householdsAtRisk: 1760,
    demandLift: 24,
    confidence: 79,
    predictedWindow: 'Next 3-5 days',
    contributingFactors: ['Rental stress', 'Low pantry coverage'],
    alertReason: 'High rental stress and low local pantry coverage indicate an upcoming demand spike.',
  },
  {
    postcode: '3051',
    suburb: 'North Melbourne',
    council: 'City of Melbourne',
    pressureScore: 88,
    householdsAtRisk: 1690,
    demandLift: 21,
    confidence: 77,
    predictedWindow: 'Within 7 days',
    contributingFactors: ['Clinic referrals', 'Limited nearby supply'],
    alertReason: 'Clinic referrals are trending up while nearby active supply remains limited.',
  },
  {
    postcode: '3182',
    suburb: 'St Kilda East',
    council: 'Port Phillip',
    pressureScore: 86,
    householdsAtRisk: 1490,
    demandLift: 19,
    confidence: 75,
    predictedWindow: 'Next week',
    contributingFactors: ['Evening demand', 'Fewer same-day surplus offers'],
    alertReason: 'Evening demand is rising and same-day surplus offers have dropped this week.',
  },
  {
    postcode: '3001',
    suburb: 'West Melbourne',
    council: 'City of Melbourne',
    pressureScore: 84,
    householdsAtRisk: 1540,
    demandLift: 18,
    confidence: 74,
    predictedWindow: 'Within 10 days',
    contributingFactors: ['Student support requests', 'Pantry reliance'],
    alertReason: 'Student support requests and pantry reliance are tracking above weekly baseline.',
  },
]
