export const hotspotSampleZones = [
  {
    postcode: '3004',
    region: 'Inner Melbourne',
    seifaScore: 962,
    resourceRequirement: 88,
    activeListings: 0,
    estimatedPopulationInNeed: 1760,
    distanceToDonorKm: 3.2,
    nearestHub: { name: 'South Melbourne Pantry', distanceKm: 4.1 },
    shortageItems: [
      { category: 'Prepared meals', shortfallPortions: 330 },
      { category: 'Fresh produce', shortfallPortions: 280 },
      { category: 'Dairy', shortfallPortions: 90, isSurplus: true },
    ],
  },
  {
    postcode: '3001',
    region: 'Inner Melbourne',
    seifaScore: 948,
    resourceRequirement: 92,
    activeListings: 0,
    estimatedPopulationInNeed: 1920,
    distanceToDonorKm: 5.8,
    nearestHub: { name: 'Docklands Relief Hub', distanceKm: 5.5 },
    shortageItems: [
      { category: 'Pantry staples', shortfallPortions: 360 },
      { category: 'Infant food', shortfallPortions: 120 },
      { category: 'Baked goods', shortfallPortions: 70, isSurplus: true },
    ],
  },
  {
    postcode: '3051',
    region: 'North Melbourne',
    seifaScore: 942,
    resourceRequirement: 89,
    activeListings: 1,
    estimatedPopulationInNeed: 1490,
    distanceToDonorKm: 7.9,
    nearestHub: { name: 'Kensington Food Point', distanceKm: 3.4 },
    shortageItems: [
      { category: 'Prepared meals', shortfallPortions: 250 },
      { category: 'Fruit & veg', shortfallPortions: 190 },
      { category: 'Shelf milk', shortfallPortions: 55, isSurplus: true },
    ],
  },
  {
    postcode: '3070',
    region: 'North-East',
    seifaScore: 983,
    resourceRequirement: 76,
    activeListings: 1,
    estimatedPopulationInNeed: 1210,
    distanceToDonorKm: 10.4,
    nearestHub: { name: 'Northcote Community Kitchen', distanceKm: 2.8 },
    shortageItems: [
      { category: 'Pantry staples', shortfallPortions: 180 },
      { category: 'Protein packs', shortfallPortions: 140 },
      { category: 'Fresh bread', shortfallPortions: 60, isSurplus: true },
    ],
  },
  {
    postcode: '3175',
    region: 'South-East',
    seifaScore: 930,
    resourceRequirement: 89,
    activeListings: 0,
    estimatedPopulationInNeed: 2040,
    distanceToDonorKm: 24.7,
    nearestHub: { name: 'Dandenong Relief Centre', distanceKm: 2.2 },
    shortageItems: [
      { category: 'Prepared meals', shortfallPortions: 420 },
      { category: 'Long-life dairy', shortfallPortions: 220 },
      { category: 'Baked snacks', shortfallPortions: 80, isSurplus: true },
    ],
  },
  {
    postcode: '3021',
    region: 'West',
    seifaScore: 905,
    resourceRequirement: 95,
    activeListings: 0,
    estimatedPopulationInNeed: 2280,
    distanceToDonorKm: 19.3,
    nearestHub: { name: 'Sunshine Support Depot', distanceKm: 4.8 },
    shortageItems: [
      { category: 'Protein packs', shortfallPortions: 410 },
      { category: 'Baby food', shortfallPortions: 170 },
      { category: 'Dairy desserts', shortfallPortions: 65, isSurplus: true },
    ],
  },
  {
    postcode: '3350',
    region: 'Regional West',
    seifaScore: 944,
    resourceRequirement: 84,
    activeListings: 0,
    estimatedPopulationInNeed: 1670,
    distanceToDonorKm: 111.4,
    nearestHub: { name: 'Ballarat Community Pantry', distanceKm: 7.1 },
    shortageItems: [
      { category: 'Pantry staples', shortfallPortions: 300 },
      { category: 'Prepared meals', shortfallPortions: 210 },
      { category: 'Fruit boxes', shortfallPortions: 70, isSurplus: true },
    ],
  },
  {
    postcode: '3630',
    region: 'Regional North',
    seifaScore: 938,
    resourceRequirement: 88,
    activeListings: 1,
    estimatedPopulationInNeed: 1380,
    distanceToDonorKm: 183.5,
    nearestHub: { name: 'Shepparton Food Link', distanceKm: 5.6 },
    shortageItems: [
      { category: 'Shelf-stable meals', shortfallPortions: 205 },
      { category: 'Infant formula', shortfallPortions: 90 },
      { category: 'Bakery sweets', shortfallPortions: 50, isSurplus: true },
    ],
  },
]
