export const SUPPLY_GAP_DATA_SOURCE = 'sample'

export const SUPPLY_GAP_ZONE_SAMPLES = [
  {
    postcode: '3004',
    suburb: 'Southbank & Domain',
    council: 'City of Melbourne',
    pressureScore: 91,
    seifaScore: 911,
    estimatedPopulationInNeed: 1760,
    nearestSupplyPoint: 'South Melbourne Hub',
    nearestSupplyDistanceKm: 4.2,
    baselineActiveListings: 0,
    baselineActivePortions: 0,
  },
  {
    postcode: '3051',
    suburb: 'North Melbourne',
    council: 'City of Melbourne',
    pressureScore: 88,
    seifaScore: 948,
    estimatedPopulationInNeed: 1690,
    nearestSupplyPoint: 'Queen Victoria Pantry',
    nearestSupplyDistanceKm: 3.4,
    baselineActiveListings: 3,
    baselineActivePortions: 248,
  },
  {
    postcode: '3182',
    suburb: 'St Kilda East',
    council: 'Port Phillip',
    pressureScore: 86,
    seifaScore: 923,
    estimatedPopulationInNeed: 1490,
    nearestSupplyPoint: 'Balaclava Community Store',
    nearestSupplyDistanceKm: 5.1,
    baselineActiveListings: 3,
    baselineActivePortions: 226,
  },
  {
    postcode: '3001',
    suburb: 'West Melbourne',
    council: 'City of Melbourne',
    pressureScore: 84,
    seifaScore: 955,
    estimatedPopulationInNeed: 1540,
    nearestSupplyPoint: 'Docklands Relief Point',
    nearestSupplyDistanceKm: 2.8,
    baselineActiveListings: 0,
    baselineActivePortions: 0,
  },
  {
    postcode: '3072',
    suburb: 'Preston South',
    council: 'Darebin',
    pressureScore: 79,
    seifaScore: 967,
    estimatedPopulationInNeed: 1320,
    nearestSupplyPoint: 'Preston Market Pickup',
    nearestSupplyDistanceKm: 6.4,
    baselineActiveListings: 4,
    baselineActivePortions: 302,
  },
  {
    postcode: '3163',
    suburb: 'Carnegie',
    council: 'Glen Eira',
    pressureScore: 67,
    seifaScore: 1004,
    estimatedPopulationInNeed: 940,
    nearestSupplyPoint: 'Carnegie Central Pantry',
    nearestSupplyDistanceKm: 1.7,
    baselineActiveListings: 5,
    baselineActivePortions: 270,
  },
]
