"""
OutbackSHare — Victorian Regional Postcode Generator
====================================================
Source: https://immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list/regional-postcodes

Expands Victorian Category 2 and Category 3 postcode ranges into a flat list
and generates:
  1. A CSV file : vic_regional_postcodes.csv
  2. A SQL seed file: eed_region_categories.sql   

Usage:
    python generate_vic_postcodes.py
"""

# ── Postcode range definitions (from Home Affairs table, Victoria rows) ──────

VIC_RANGES = {
    "Cities and Major Regional Centres": [
        (3211, 3232),
        (3235, 3235),
        (3240, 3240),
        (3328, 3328),
        (3330, 3333),
        (3340, 3340),
        (3342, 3342),
    ],
    "Regional Centres and Other Regional Areas": [
        (3097, 3099),
        (3139, 3139),
        (3233, 3234),
        (3236, 3239),
        (3241, 3325),
        (3329, 3329),
        (3334, 3334),
        (3341, 3341),
        (3345, 3424),
        (3430, 3799),
        (3809, 3909),
        (3912, 3971),
        (3978, 3996),
    ],
}

# ── Expand ranges into flat postcode list ────────────────────────────────────

def expand_ranges(category_ranges: dict) -> list[dict]:
    """Expand all ranges into individual postcode records."""
    records = []
    for category, ranges in category_ranges.items():
        for start, end in ranges:
            for postcode in range(start, end + 1):
                records.append({
                    "postcode": str(postcode).zfill(4),
                    "regional_category": category,
                    "state": "VIC",
                })
    # Sort by postcode numerically
    records.sort(key=lambda r: int(r["postcode"]))
    return records


# ── Write CSV ────────────────────────────────────────────────────────────────

def write_csv(records: list[dict], filepath: str) -> None:
    import csv
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["postcode", "regional_category", "state"])
        writer.writeheader()
        writer.writerows(records)
    print(f" CSV written → {filepath}  ({len(records)} postcodes)")


# ── Write SQL seed file ──────────────────────────────────────────────────────

def write_sql(records: list[dict], filepath: str) -> None:
    lines = [
        "-- outbackshare: seed region_categories with Victorian regional postcodes",
        "-- Source: https://immi.homeaffairs.gov.au/visas/working-in-australia/skill-occupation-list/regional-postcodes",
        "-- Generated by generate_vic_postcodes.py",
        "",
        "INSERT INTO region_categories (postcode, regional_category)",
        "VALUES",
    ]

    value_lines = []
    for record in records:
        postcode = record["postcode"]
        category = record["regional_category"].replace("'", "''")  # escape single quotes
        value_lines.append(f"  ('{postcode}', '{category}')")

    lines.append(",\n".join(value_lines))
    lines.append("ON CONFLICT (postcode) DO UPDATE")
    lines.append("  SET regional_category = EXCLUDED.regional_category;")
    lines.append("")
    lines.append(f"-- Total postcodes inserted: {len(records)}")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"SQL written  → {filepath}  ({len(records)} INSERT rows)")


# ── Summary stats ────────────────────────────────────────────────────────────

def print_summary(records: list[dict]) -> None:
    from collections import Counter
    counts = Counter(r["regional_category"] for r in records)
    print("\n── Summary ──────────────────────────────────────────")
    print(f"  Total Victorian regional postcodes : {len(records)}")
    for category, count in counts.items():
        print(f"  {category[:50]:<50} : {count}")
    print(f"\n  Postcode range : {records[0]['postcode']} → {records[-1]['postcode']}")
    print("─────────────────────────────────────────────────────\n")


# ── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    records = expand_ranges(VIC_RANGES)
    print_summary(records)
    write_csv(records, "vic_regional_postcodes.csv")
    write_sql(records, "seed_region_categories.sql")
    print("\nDone. Both files are ready.")
